name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:

    name: uv-master-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4"

    - name: Install dependencies
      run: uv sync --verbose

    - name: Build package
      run: uv build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
